services:
  - type: web
    name: document-qa-frontend
    env: node
    buildCommand: npm install && npm run build
    staticPublishPath: ./out
    envVars:
      - key: NODE_VERSION
        value: 20.x
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"